// Generated by the Blazor I18n Text compiler
namespace Kikartan.BlazorApp.I18nText
{
    public partial class Foods : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Whey Protein Powder"</summary>
        public string WheyProteinPowder;
    }
}
