// Generated by the Blazor I18n Text compiler
namespace Kikartan.BlazorApp.I18nText
{
    public partial class NutrientFacts : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Carbohydrate"</summary>
        public string Carbohydrate;

        /// <summary>"Energy"</summary>
        public string Energy;

        /// <summary>"Fat"</summary>
        public string Fat;

        /// <summary>"Fiber"</summary>
        public string Fiber;

        /// <summary>"Nutrients"</summary>
        public string Nutrients;

        /// <summary>"Protein"</summary>
        public string Protein;

        /// <summary>"Saturated Fat"</summary>
        public string SaturatedFat;

        /// <summary>"Vegan"</summary>
        public string Vegan;
    }
}
